// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrmyzcuxwekllvbdbmnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybXl6Y3V4d2VrbGx2YmRibW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzI3NjUsImV4cCI6MjA2MDk0ODc2NX0.g4Dl8YUc-QAjLBWULgPqupWbNufqMkd6n5NN3kyQ3ZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);